name = "propertyfinder-frontend"
compatibility_date = "2024-08-17"

[env.production]
name = "properties-gursimanoor-com"
compatibility_date = "2024-08-17"

[env.production.vars]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://properties.gursimanoor.com/api"

[env.production.routes]
zone_name = "gursimanoor.com"
custom_domain = "properties.gursimanoor.com"
