version: '3.8'

services:
  # PostgreSQL with PostGIS extension
  postgres:
    image: postgis/postgis:15-3.3
    container_name: propertyfinder_postgres_local
    environment:
      POSTGRES_DB: propertyfinder
      POSTGRES_USER: propertyfinder
      POSTGRES_PASSWORD: propertyfinder123
    ports:
      - "5432:5432"  # Accessible from localhost
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U propertyfinder"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # FastAPI backend
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: propertyfinder_api_local
    environment:
      DATABASE_URL: postgresql://propertyfinder:propertyfinder123@postgres:5432/propertyfinder
      ZILLOW_API_KEY: mock_key
      CENSUS_API_KEY: mock_key
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
    ports:
      - "8080:8080"  # Backend API on port 8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../backend:/app
      - ../data:/app/data
    command: python main.py
    restart: unless-stopped

volumes:
  postgres_data_local:
