version: '3.8'

services:
  # PostgreSQL with PostGIS extension
  postgres:
    image: postgis/postgis:15-3.3
    container_name: propertyfinder_postgres_prod
    environment:
      POSTGRES_DB: propertyfinder
      POSTGRES_USER: propertyfinder
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U propertyfinder"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # FastAPI backend
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: propertyfinder_api_prod
    environment:
      DATABASE_URL: postgresql://propertyfinder:${POSTGRES_PASSWORD}@postgres:5432/propertyfinder
      ZILLOW_API_KEY: ${ZILLOW_API_KEY}
      CENSUS_API_KEY: ${CENSUS_API_KEY}
      NODE_ENV: production
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./data:/app/data
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: propertyfinder_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data_prod:
